# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

#Submit DAST Scan to Veracode
- task: CmdLine@2
  displayName: VC - Install Veracode Auth
  inputs:
    script: |
      pip install veracode-api-signing

- task: CmdLine@2
  displayName: VC - Apply Creds
  inputs:
    script: |
      echo [default] >> credentials.txt
      echo veracode_api_key_id = $(VERACODE_API_KEY_ID) >> credentials.txt
      echo veracode_api_key_secret = $(VERACODE_API_KEY_SECRET) >> credentials.txt
      mkdir c:\Users\VssAdministrator\.veracode
      cp credentials.txt c:\Users\VssAdministrator\.veracode\credentials

- task: CmdLine@2
  displayName: VC - Create DA json
  inputs:
    script: |
      echo  { >> da_scan.json
      echo    "name": "UID | $(build.buildNumber)", >> da_scan.json
      echo    "scans": [ >> da_scan.json
      echo     { >> da_scan.json
      echo       "scan_config_request": { >> da_scan.json
      echo         "target_url": { >> da_scan.json
      echo           "url": "http://verademo.tsaekao.vuln.sa.veracode.io/verademo", >> da_scan.json
      echo           "http_and_https": true, >> da_scan.json
      echo           "directory_restriction_type": "DIRECTORY_AND_SUBDIRECTORY" >> da_scan.json
      echo         }, >> da_scan.json
      echo         "auth_configuration": { >> da_scan.json
      echo           "authentications": { >> da_scan.json
      echo             "FORM": { >> da_scan.json
      echo               "login_script_name": "login-script.side", >> da_scan.json
      echo               "login_script_data": { >> da_scan.json
      echo                 "script_body": " {
          "id": "4b5fbc82-26b1-4291-a90b-f35967cd4a13",
          "version": "2.0",
          "name": "Verademo DAST",
          "url": "http://verademo.tsaekao.vuln.sa.veracode.io/verademo",
          "tests": [{
            "id": "b254886b-0204-4203-b8fc-b25adbb5247c",
            "name": "Verademo DAST Login Script_20230927",
            "commands": [{
              "id": "abaf3ea7-fe92-439f-877d-85f84de5dd62",
              "comment": "",
              "command": "open",
              "target": "http://verademo.tsaekao.vuln.sa.veracode.io/verademo/login",
              "targets": [],
              "value": ""
            }, {
              "id": "6a1d6c12-778a-4dc9-94ff-1acd94fae96b",
              "comment": "",
              "command": "setWindowSize",
              "target": "1920x738",
              "targets": [],
              "value": ""
            }, {
              "id": "933cf820-e6f7-43c5-a865-bfab99ff39ac",
              "comment": "",
              "command": "click",
              "target": "name=user",
              "targets": [
                ["name=user", "name"],
                ["css=tr:nth-child(1) .form-control", "css:finder"],
                ["xpath=//input[@name='user']", "xpath:attributes"],
                ["xpath=//div/input", "xpath:position"]
              ],
              "value": ""
            }, {
              "id": "b7f0765b-cced-49d8-a885-866bd2a2a67f",
              "comment": "",
              "command": "type",
              "target": "name=user",
              "targets": [
                ["name=user", "name"],
                ["css=tr:nth-child(1) .form-control", "css:finder"],
                ["xpath=//input[@name='user']", "xpath:attributes"],
                ["xpath=//div/input", "xpath:position"]
              ],
              "value": "admin"
            }, {
              "id": "ccf839bb-277a-4191-9be4-18d6fb537327",
              "comment": "",
              "command": "click",
              "target": "name=password",
              "targets": [
                ["name=password", "name"],
                ["css=tr:nth-child(2) .form-control", "css:finder"],
                ["xpath=//input[@name='password']", "xpath:attributes"],
                ["xpath=//tr[2]/td[2]/div/input", "xpath:position"]
              ],
              "value": ""
            }, {
              "id": "6adb2116-b85c-4854-9eb8-617b82f5245a",
              "comment": "",
              "command": "type",
              "target": "name=password",
              "targets": [
                ["name=password", "name"],
                ["css=tr:nth-child(2) .form-control", "css:finder"],
                ["xpath=//input[@name='password']", "xpath:attributes"],
                ["xpath=//tr[2]/td[2]/div/input", "xpath:position"]
              ],
              "value": "admin"
            }, {
              "id": "906990a5-fc89-441d-88bf-5a1787f9bf8c",
              "comment": "",
              "command": "click",
              "target": "id=login",
              "targets": [
                ["id=login", "id"],
                ["name=Login", "name"],
                ["css=#login", "css:finder"],
                ["xpath=//button[@id='login']", "xpath:attributes"],
                ["xpath=//button", "xpath:position"],
                ["xpath=//button[contains(.,'Login')]", "xpath:innerText"]
              ],
              "value": ""
            }, {
              "id": "3099fd8d-3fc6-481b-b1a6-a56e009b12fd",
              "comment": "",
              "command": "assertText",
              "target": "linkText=Logout",
              "targets": [
                ["linkText=Logout", "linkText"],
                ["css=li:nth-child(5) > a", "css:finder"],
                ["xpath=//a[contains(text(),'Logout')]", "xpath:link"],
                ["xpath=//a[contains(@href, 'logout')]", "xpath:href"],
                ["xpath=//li[5]/a", "xpath:position"],
                ["xpath=//a[contains(.,'Logout')]", "xpath:innerText"]
              ],
              "value": "Logout"
            }]
          }],
          "suites": [{
            "id": "7b7c6c12-9b58-4f00-9da4-bce02aa072a0",
            "name": "Default Suite",
            "persistSession": false,
            "parallel": false,
            "timeout": 300,
            "tests": ["b254886b-0204-4203-b8fc-b25adbb5247c"]
          }],
          "urls": ["http://verademo.tsaekao.vuln.sa.veracode.io/verademo"],
          "plugins": [] } ", >> da_scan.json
      echo                 "script_type": "SELENIUM" >> da_scan.json
      echo               }, >> da_scan.json
      echo               "authtype": "FORM" >> da_scan.json
      echo             } >> da_scan.json
      echo           } >> da_scan.json
      echo         }, >> da_scan.json
      echo         "scan_setting": { >> da_scan.json
      echo           "advanced_mode": true, >> da_scan.json
      echo           "browser_version": "CHROME_DEFAULT" >> da_scan.json
      echo         }, >> da_scan.json
      echo         "crawl_configuration": { >> da_scan.json
      echo           "scripts": [], >> da_scan.json
      echo           "disabled": false >> da_scan.json
      echo         } >> da_scan.json
      echo       }, >> da_scan.json
      echo       "internal_scan_configuration": { >> da_scan.json
      echo         "enabled": false, >> da_scan.json
      echo         "gateway_id": "0be0990a-4838-4a33-a49d-70c72f3xxxxx", >> da_scan.json
      echo         "endpoint_id": "563f8321-6641-4706-a7ac-afc7b4fxxxxx" >> da_scan.json
      echo       } >> da_scan.json
      echo     } >> da_scan.json
      echo   ], >> da_scan.json
      echo    "schedule": { >> da_scan.json
      echo      "now": true, >> da_scan.json
      echo      "duration": { >> da_scan.json
      echo        "length": 1, >> da_scan.json
      echo        "unit": "DAY" >> da_scan.json
      echo      }, >> da_scan.json
      echo      "end_date": "", >> da_scan.json
      echo      "schedule_status": "ACTIVE" >> da_scan.json
      echo    } >> da_scan.json
      echo  } >> da_scan.json

- task: PythonScript@0
  displayName: VC - kick off DAST scan
  inputs:
    scriptSource: 'inline'
    script: |
      import sys
      import json
      import requests
      from veracode_api_signing.plugin_requests import RequestsAuthPluginVeracodeHMAC
      
      
      api_base = "https://api.veracode.com/was/configservice/v1"
      headers = {"User-Agent": "Start DA Scan Example", 'Content-type': 'application/json'}
      
      
      if __name__ == "__main__":
      
          try:
              contents = open('da_scan.json', 'rb').read()
              print(contents)
              response = requests.post(api_base + "/analyses", auth=RequestsAuthPluginVeracodeHMAC(), data=contents, headers=headers)
          except requests.RequestException as e:
              print("Failed...")
              print(e)
              sys.exit(1)
      
          if response.ok:
              print(response.status_code)
              print(response.content)
      
          else:
              print(response.status_code)
              print(response.content)